import { TCard } from "./types";

export const data: TCard[] = [
  //Mythics
  { name: "Atraxa, Grand Unifier", owned: 0, rarity: "M" },
  { name: "All Will Be One", owned: 0, rarity: "M" },
  { name: "Capricious Hellraiser", owned: 0, rarity: "M" },
  { name: "Drivnod, Carnage Dominus", owned: 0, rarity: "M" },
  { name: "Elesh Norn, Mother of Machines", owned: 0, rarity: "M" },
  { name: "Ichormoon Gauntlet", owned: 0, rarity: "M" },
  { name: "Jace, the Perfected Mind", owned: 0, rarity: "M" },
  { name: "Lukka, Bound to Ruin", owned: 0, rarity: "M" },
  { name: "Mondrak, Glory Dominus", owned: 0, rarity: "M" },
  { name: "Nahiri, the Unforgiving", owned: 0, rarity: "M" },
  { name: "Nissa, Ascended Animist", owned: 0, rarity: "M" },
  { name: "Phyrexian Obliterator", owned: 0, rarity: "M" },
  { name: "Phyrexian Vindicator", owned: 0, rarity: "M" },
  { name: "Solphim, Mayhem Dominus", owned: 0, rarity: "M" },
  { name: "Staff of Compleation", owned: 0, rarity: "M" },
  { name: "Sword of Forge and Frontier", owned: 0, rarity: "M" },
  { name: "Tekuthal, Inquiry Dominus", owned: 0, rarity: "M" },
  { name: "Tyrranax Rex", owned: 0, rarity: "M" },
  { name: "Vraska, Betrayal's Sting", owned: 0, rarity: "M" },
  { name: "Zopandrel, Hunger Dominus", owned: 0, rarity: "M" },
  //Rares
  { name: "Archfiend of the Dross", owned: 0, rarity: "R" },
  { name: "Argentum Masticore", owned: 0, rarity: "R" },
  { name: "Blackcleave Cliffs", owned: 0, rarity: "R" },
  { name: "Black Sun's Twilight", owned: 0, rarity: "R" },
  { name: "Blade of Shared Souls", owned: 0, rarity: "R" },
  { name: "Bloated Contaminator", owned: 0, rarity: "R" },
  { name: "Blue Sun's Twilight", owned: 0, rarity: "R" },
  { name: "Conduit of Worlds", owned: 0, rarity: "R" },
  { name: "Copperline Gorge", owned: 0, rarity: "R" },
  { name: "Darkslic Shores", owned: 0, rarity: "R" },
  { name: "Dragonwing Glider", owned: 0, rarity: "R" },
  { name: "Encroaching Mycosynth", owned: 0, rarity: "R" },
  { name: "Evolved Spinoderm", owned: 0, rarity: "R" },
  { name: "Ezuri, Stalker of Spheres", owned: 0, rarity: "R" },
  { name: "Geth, Thane of Contracts", owned: 0, rarity: "R" },
  { name: "Glissa, Sunslayer", owned: 0, rarity: "R" },
  { name: "Goliath Hatchery NOT BOOSTERS", owned: 0, rarity: "R" },
  { name: "Graaz, Unstoppable Juggernaut", owned: 0, rarity: "R" },
  { name: "Green Sun's Twilight", owned: 0, rarity: "R" },
  { name: "Jor Kadeen, First Goldwarden", owned: 0, rarity: "R" },
  { name: "Kaito, Dancing Shadow", owned: 0, rarity: "R" },
  { name: "Karumonix, the Rat King", owned: 0, rarity: "R" },
  { name: "Kaya, Intangible Slayer", owned: 0, rarity: "R" },
  { name: "Khemba, Kha Enduring", owned: 0, rarity: "R" },
  { name: "Khethek, Crucible Goliath", owned: 0, rarity: "R" },
  { name: "Khemba, Kha Enduring NOT BOOSTERS", owned: 0, rarity: "R" },
  { name: "Koth, Fire of Resistance", owned: 0, rarity: "R" },
  { name: "Malcator, Purity Overseer", owned: 0, rarity: "R" },
  { name: "Melira, the Living Cure", owned: 0, rarity: "R" },
  { name: "Mercurial Spelldancer", owned: 0, rarity: "R" },
  { name: "Migloz, Maze Crusher", owned: 0, rarity: "R" },
  { name: "Mindsplice Apparatus", owned: 0, rarity: "R" },
  { name: "Mirran Safehouse", owned: 0, rarity: "R" },
  { name: "Mirrex", owned: 0, rarity: "R" },
  { name: "Mite Overseer NOT BOOSTERS", owned: 0, rarity: "R" },
  { name: "Monument to Perfection", owned: 0, rarity: "R" },
  { name: "Norn's Wellspring", owned: 0, rarity: "R" },
  { name: "Ovika, Enigma Goliath", owned: 0, rarity: "R" },
  { name: "Phyrexian Arena", owned: 0, rarity: "R" },
  { name: "Razorverge Thicket", owned: 0, rarity: "R" },
  { name: "Red Sun's Twilight", owned: 0, rarity: "R" },
  { name: "Rhuk, Hexgold Nabber NOT BOOSTERS", owned: 0, rarity: "R" },
  { name: "Ria Ivor, Bane of Bladehold", owned: 0, rarity: "R" },
  { name: "Seachrome Coast", owned: 0, rarity: "R" },
  { name: "Serum Sovereign NOT BOOSTERS", owned: 0, rarity: "R" },
  { name: "Skrelv, Defector Mite", owned: 0, rarity: "R" },
  { name: "Skrelv's Hive'", owned: 0, rarity: "R" },
  { name: "Slobad, Iron Goblin", owned: 0, rarity: "R" },
  { name: "Soulless Jailer", owned: 0, rarity: "R" },
  { name: "Tablet of Compleation", owned: 0, rarity: "R" },
  { name: "The Eternal Wanderer", owned: 0, rarity: "R" },
  { name: "The Filigree Sylex", owned: 0, rarity: "R" },
  { name: "The Monumental Facade", owned: 0, rarity: "R" },
  { name: "The Mycosynt Gardens", owned: 0, rarity: "R" },
  { name: "The Seedcore", owned: 0, rarity: "R" },
  { name: "Thrun, Breaker of Silence", owned: 0, rarity: "R" },
  { name: "Tyvar, Jubilant Brawler", owned: 0, rarity: "R" },
  { name: "Unctus, Grand Metatect", owned: 0, rarity: "R" },
  { name: "Urabrask's Forge", owned: 0, rarity: "R" },
  { name: "Venerated Rotpriest", owned: 0, rarity: "R" },
  { name: "Venser, Corpse Puppet", owned: 0, rarity: "R" },
  { name: "Vindictive Flamestoker", owned: 0, rarity: "R" },
  { name: "Vraan, Executioner Thane", owned: 0, rarity: "R" },
  { name: "White Sun's Twilight", owned: 0, rarity: "R" },
  { name: "Zenith Chronicler", owned: 0, rarity: "R" },
];
